
name: Python application

on:
    push:
      branches: [ "develop" ]

jobs:
  build:
    runs-on:  deploy-linux 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          $rootPath = Get-Location
          $serverAddonsPath = "$rootPath\server_addon"
          $buildFolderPath = Join-Path -Path $rootPath -ChildPath "build"
          # Create the build folder if it doesn't exist
          if (-not (Test-Path -Path $buildFolderPath -PathType Container)) {
            New-Item -Path $buildFolderPath -ItemType Directory | Out-Null
          }
          $addonItems = Get-ChildItem -Path $serverAddonsPath
          foreach ($addonItem in $addonItems) {
            if ($addonItem.PSIsContainer) {
              $versionFilePath = Join-Path -Path $addonItem.FullName -ChildPath "server/version.py"
              if (Test-Path -Path $versionFilePath -PathType Leaf) {
                $versionFileContent = Get-Content -Path $versionFilePath
                $versionPattern1 = '__version__ = "(?<version>\d+\.\d+\.\d+)"'
                $versionPattern2 = '__version__ = "(?<version>\d+\.\d+\.\d+-\w+\.\d+)"'
                $versionMatch1 = [regex]::Match($versionFileContent, $versionPattern1)
                $versionMatch2 = [regex]::Match($versionFileContent, $versionPattern2)
                $versionMatch = [regex]::Match($versionFileContent, $versionPattern)
                if ($versionMatch1.Success) {
                  $version = $versionMatch1.Groups["version"].Value
                } elseif ($versionMatch2.Success) {
                  $version = $versionMatch2.Groups["version"].Value
                } else {
                  $version = "Version not found"
                }
                $addonBuildFolderPath = Join-Path -Path $buildFolderPath -ChildPath "$addonItem/$version"
                # Create the addon build folder if it doesn't exist
                if (-not (Test-Path -Path $addonBuildFolderPath -PathType Container)) {
                  New-Item -Path $addonBuildFolderPath -ItemType Directory | Out-Null
                }
                # Copy the contents of the addon item to the addon build folder
                Copy-Item -Path "$serverAddonsPath/$addonItem/server/*" -Destination $addonBuildFolderPath -Recurse -Force
              }
            }
          }
      - name: Upload to S3
        run: |
          $current_dir = Get-Location
          $awsCliPath = "C:\Program Files\Amazon\AWSCLIV2\aws.exe"
          $sourcePath = "$current_dir/build"
          $destinationPath = "${{ vars.S3_BUCKET }}/${{ vars.BUILDS }}/server-addons"
          & $awsCliPath s3 sync $sourcePath $destinationPath
          echo "$sourcePath --> $destinationPath"

  depoly:
    runs-on: deploy-linux
    needs: build
    steps:
    - name: Download from S3
      run: |
        linuxBuildVersion="${{ vars.BUILD_VERSION }}.${{ github.run_number }}"          
        sourcePath="${{ vars.S3_BUCKET }}/${{ vars.BUILDS }}/server-addons"       
        destinationPath="${{ vars.S3_BUCKET }}/${{ vars.BUILDS }}/server-addons"
        rm -rf   $devPath
        mkdir -p $devPath

        aws s3 cp $sourcePath $destinationPath --recursive           
        cp -al --no-preserve=mode $destinationPath/*  $devPath           